name: "CI"

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 check-test-build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: "16"
   - run: yarn install --frozen-lockfile
   - run: yarn format:check
   - run: yarn lint
   - run: yarn test
   - run: yarn build
